sudo: required
language: python
cache: pip
python:
- 3.6
- 3.7
- 3.8
before_install:
- sudo add-apt-repository -y ppa:maxmind/ppa
- sudo apt-get update
- sudo apt-get install geoipupdate
- sudo rm -f /etc/GeoIP.conf
- echo "UserId $MM_USERID" | sudo tee /etc/GeoIP.conf > /dev/null
- echo "LicenseKey $MM_LIC" | sudo tee -a /etc/GeoIP.conf > /dev/null
- echo 'ProductIds GeoLite2-Country GeoLite2-City GeoLite2-ASN' | sudo tee -a /etc/GeoIP.conf
  > /dev/null
- sudo geoipupdate
- pip install -r dev_requirements.txt
script:
- python setup.py develop
- python setup.py test
- python setup.py sdist bdist bdist_wheel
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: pypi
  user: __token__
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.8"
  password:
    secure: BLcEVJ+yMcvZUe5vPu/BMUYk65faJ2vWE8blkiZv4UAu5FLGu61ehQps4bfbPWKGLPvS70GF4j+JIbe/l0HfEwRbXMJm6pRVrTyEWskmuLJx8QRT3Ula0rt8k9b/EzXHXF4ZVx0bwX5fyFOg2OsJjHW/N2tix9/ld4QI4ZxldIkXxhV6G9mGO8aNSSwe05VIx3VSWTAnvi0rV4RzC+7x2kDqXGf4tawRNDF22S7Iuz1k6+zBVocPDSyIyJw3Q1ZqQPrrXungOUlpMtyyJeGY5ZnSTOPMP+KASQh/WqE25ZejsV7rqfuw/OT0c9ZNM5JY0bO0mIyDLRX6fvNkuhvwZc1au79VY/RGfdp+0fV02CFfSt4BZCaVhlXZSo71FufiK3KRwgLWdDEJrG2delM7IdXI1apdQvp+fdRexYTpW1eT3sotGdyCWJ/OiBkGQzmxXSUcUx2cLy15Wrd2q2ctPlzX1VuNu//R18A6Tofespny2eq/S4JJ26qaGu3FKYdnAN+z0YB0jHZosZatlq3pdeYCbd8zifYX2t2bf1onKvMOHhft5b5iL+1SWI5F1yb0xVj8V/ng7BktmbWOH4gok+JBPRxqXvIBU00mQR2A3MiMyZVum25mIiFUxrKeRtcyhagKzNX0Cjvv8D/PLtIAErs2T4d4cPg7aXd4bhQgO4g=
env:
  global:
  - secure: 1Pxfem5P054NiAGcSTgJf5vtLbUuUZHQa3RHMcKE7qiP7x2SYf9sw2MUPsHcHmNtQr1ZgQCBwXJcz0+G69WbthZQCMCnA9XEbG0sxDaxYLR8w5JjRNMnqu+V66dmAs6PXXUGiNgO06T584AWuzjI/prCg6EWiRySj0CeCdSnMpr3mvjRPJbvBWUF1pCy2ZW/iJ5MvKlxhYhjuBgNA6QLYLt0t9sSkP9uwr43EB4yyXZu5yiGtMkMx8jE1BmHf+Q1fHuLBDRw1pc6zA6/w2CJmCwb+E0/LxkpF8ku85sCOAJQzivsjH9EMElSOcvbkaEPJFkSXRZIGHnVHmKugLHo2H3G63G//qc3PixrtvA7lfrMOveJ5epgdQCIdyE9h5xf73MxbMoIJmwtB53NVI11+C9LtntXTlTS9lCrp/3F/M8j1Hv5T9jNnHv0mpLFKLjjX+vMplMOgntch1o2yk+ImoSblWsRig/oF2eByoLYZroQv/5vBnwTIm98NecWgeoUhN2lDIsMxX4x9D6c0gdUukLK5fiYHVAYlOEWcdimKiE5NeuCS0jP+reCHFqywiOZVkf8DTTN/FubiM3vpiN+wcPkZsT4UjxwU6bHjWsL2zIFr/aVC54xSKd2Rijhm8cDH4bMPGS5qGI1VK2rJalDklp4DWN16VOf3X2OBgYYO5k=
  - secure: VCckvuXv53tObKTbbI/LbZkpgunwffLxgFuwNMdBClNXjdzJxgSQz1H0cswVFtS1vM0a8rl77zHwfh4JX3sGg6NI0xlof6gPW0uD6xw6OT4q99YN/sTIxFC/sUs5cnYRFO2Hae1fL/yTyqEnlS3iQIBrLXIDxUEtMbHvsgfJ848sh9zb3fawliaCArThY1/aB/vMcvrFzRZEZ/q07hjlfXSqOsk8KB45ncagTw9lvM6tVOe7XLZ46vXgkPUtYUEwmhgIq5+c/KPEI2v6XwU2U4c8q64MxbDtpTF6pxKcXmDDDhSJ+mTs3smEsJ6Dd1AIVetCHPZuIE9BlUWflF/6Ch78qPPcjnqZgBL5qT1aex2eOUT2HDg1MkKcHfx79sRbVFz9yWrH+B5eH/2wjDFViA495dDNKLZvXAMKb37dQIuHV0fFp4ncidHPWiWvhlADoNP3YzQC4jLDbnzb1L4Ku8zwJoVL+18dUK0EAL+bHdBpxV1EAoa19UTghmL/dNK46I8NY9N57b7Dwz3RShAYkmaRkGvCsq1BQJvFjZMeaIK5eCtvJoR9aU2eHe11ZtNfcmzTUwcm9TpjVTsqnsa4WNzzt/OlVgy1e/SojfmCegZPs6K1+EQm3m8rWfx8G5PeBylpDzM/3fxlyo2FnoOVzDy/kplcsflVdqCK9Y4QMOc=
